" ---------------------
" ENVIRONMENT 
" ---------------------

" Ensure that various options are properly set to work with the 
" Vim-related packages available in Debian.
" TODO check if Debian env first
runtime! debian.vim
" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
endif
" Don't care if this is compatible with vi
set nocompatible

" ---------------------
" TABS 
" ---------------------

" Expand all tabs to spaces
set expandtab
" Set tab width to 4
set tabstop=4
" Expand all existing tab characters to spaces
retab
" Set number of spaces for indentation
set shiftwidth=4
" Set tab width to 2 for Python, HTML, CSS only
"au FileType python,html,css setl sw=2 sts=2 et
au FileType html,css setl sw=2 sts=2 et

" ---------------------
" KEY MAPPINGS 
" ---------------------

" jj to Esc 
imap jj <Esc>
" :W<CR> to :w<CR> since I can't seem to hit :w accurately
cnoreabbrev W w
" :Q<CR> to :q<CR> since I can't seem to hit :q accurately either...
cnoreabbrev Q q

" ---------------------
" SYNTAX HIGHLIGHTING 
" ---------------------

" Enable syntax highlighting
if has("syntax")
  syntax on
endif
" Set JavaScript Template file syntax highlighting to HTML format
au BufNewFile,BufRead *.ejs set filetype=html
" Show matching brackets
set showmatch

" ---------------------
" OTHER 
" ---------------------

" Fix backspace, which sometimes doesn't work as expected by default
set backspace=2
" Line number, displacement in status bar
set ruler
" Jump to last position when reopening file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
" No sound on errors, visual bell instead
set noerrorbells
set visualbell
" Split new window to right instead of left when :split is used
set splitright

 set diffopt+=iwhite
  set diffexpr=DiffW()
  function DiffW()
    let opt = ""
     if &diffopt =~ "icase"
       let opt = opt . "-i "
     endif
     if &diffopt =~ "iwhite"
       let opt = opt . "-w " " vim uses -b by default
     endif
     silent execute "!diff -a --binary " . opt .
       \ v:fname_in . " " . v:fname_new .  " > " . v:fname_out
  endfunction
