# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=4096
SAVEHIST=4096
setopt autocd extendedglob notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename '/home/matt/.zshrc'
autoload -Uz compinit
compinit
# End of lines added by compinstall

# Tab completion from both ends
setopt completeinword

# Prompt
autoload -U colors && colors
PS1="%{$fg[red]%}%n%{$reset_color%}@%{$fg[green]%}%m %{$fg[yellow]%}%~ %{$reset_color%}%% "

# ls colors
if [[ -x "`whence -p dircolors`" ]]; then
  eval `dircolors`
  alias ls='ls -F --color=auto'
else
  alias ls='ls -F'
fi

# Better completion for killall
zstyle ':completion:*:killall:*' command 'ps -u $USER -o cmd'

# Environment variables
export EDITOR='vim'
export VISUAL='vim'

# Aliases
alias l='ls -f'
alias ls='ls -f'
alias ll='ls -lf'
alias la='ls -af'
alias ltr='ls -ltrf'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias c='clear'
alias h='history'

alias md='mkdir'
alias rd='rmdir'
